executable          	= condorzphi.sh
should_transfer_files 	= YES
arguments             	= $(script_args)
notify_user				= jasminvweiss@gmail.com
notification 			= Always

##############################################################################################################
output      = logs_zphi.$(ClusterId).$(ProcId).out
error       = logs_zphi.$(ClusterId).$(ProcId).err
log         = logs_zphi.$(ClusterId).$(ProcId).log
##############################################################################################################

request_memory 		= 7000
#request_disk			= 4 GB
on_exit_remove   		= (ExitBySignal == False) && (ExitCode == 0)
max_retries      		= 3
requirements     		= Machine =!= LastRemoteHost

##############################################################################################################
+JobFlavour="tomorrow"
#+MaxRuntime = 20
##############################################################################################################
queue