executable          	= condor.sh
should_transfer_files 	= YES
arguments             	= $(ClusterId) $(ProcId)
notify_user				= jasminvweiss@gmail.com
notification 			= Always

##############################################################################################################
output      = logs_zphi.out
error       = logs_zphi.err
log         = logs_zphi.log
##############################################################################################################

request_memory 		= 7000
#request_disk			= 4 GB
on_exit_remove   		= (ExitBySignal == False) && (ExitCode == 0)
max_retries      		= 3
requirements     		= Machine =!= LastRemoteHost

##############################################################################################################
+JobFlavour="espresso"
#+MaxRuntime = 20
##############################################################################################################
queue