executable          	= condor.sh
should_transfer_files 	= YES
arguments             	= $(ClusterId) $(ProcId)
notify_user				= jasminvweiss@gmail.com
notification 			= Always

##############################################################################################################
output      = logs.out
error       = logs.err
log         = logs.log
##############################################################################################################

#request_memory 		= 50 GB
#request_disk			= 4 GB
on_exit_remove   		= (ExitBySignal == False) && (ExitCode == 0)
max_retries      		= 3
requirements     		= Machine =!= LastRemoteHost

##############################################################################################################
+JobFlavour="testmatch"
#+MaxRuntime = 20
##############################################################################################################
queue